In [13]:
import numpy as np

In [14]:
x = np.array([10, 20, 30, 40])

In [15]:
x + 10

array([20, 30, 40, 50])

In [16]:
x

array([10, 20, 30, 40])

In [17]:
x * 2

array([20, 40, 60, 80])

In [18]:
x / 10

array([1., 2., 3., 4.])

In [19]:
np.mean(x)

np.float64(25.0)

In [20]:
np.std(x)

np.float64(11.180339887498949)

In [21]:
prices = np.array([100000, 200000, 300000, 400000])

In [22]:
min_price = np.min(prices)
max_price = np.max(prices)

In [23]:
normalized = (prices - min_price) / (max_price - min_price)
print(normalized)

[0.         0.33333333 0.66666667 1.        ]


In [24]:
actual = np.array([100, 200, 300])
predicted = np.array([110, 190, 280])

In [25]:
mse = np.mean((actual - predicted) ** 2)

In [28]:
mse

np.float64(200.0)

In [29]:
import numpy as np

sells = np.array([100000, 150000, 200000, 250000, 300000])

In [30]:
print(sells.shape)

(5,)


In [33]:
print(sells.reshape(-1,1))

[[100000]
 [150000]
 [200000]
 [250000]
 [300000]]


In [34]:
min_sells = np.min(sells)
max_sells = np.max(sells)

In [36]:
min_sells

np.int64(100000)

In [37]:
max_sells

np.int64(300000)

In [39]:
average = np.mean(sells)
average

np.float64(200000.0)

In [40]:
normalized = (sells - min_sells) / (max_sells - min_sells)
normalized

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [44]:
X = np.array([
    [20, 30000],
    [25, 40000],
    [30, 50000],
    [35, 60000],
    [40, 70000]
])

In [45]:
X.shape

(5, 2)

In [46]:
actual = np.array([100, 200, 300, 400])

predicted = np.array([110, 190, 280, 420])

In [47]:
mse = np.mean((actual - predicted) ** 2)
print(mse)

250.0
